baseURL = "https://ohbm-dic.github.io/"
languageCode = "en-us"
title = "OHBM DIC"
theme = "hugo-arcana"
copyright = "© Diversity and Inclusivity Committee, OHBM"

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"


    [params.footer]

        [[params.footer.links]]
            header = "Links"
        [[params.footer.links.links]]
            title = "OHBM Website"
            url = "https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=1"
        [[params.footer.links.links]]
            title = "OHBM Blog"
            url = "https://www.ohbmbrainmappingblog.com/"
        [[params.footer.links.links]]
            title = "OHBM OnDemand"
            url = "https://www.pathlms.com/ohbm"
        [[params.footer.links.links]]
            title = "Aperture Neuro"
            url = "https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=4121"
        [[params.footer.links.links]]
            title = "OHBM Engage"
            url = "https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=3931"
        [[params.footer.links.links]]
            title = "COBIDAS"
            url = "https://www.humanbrainmapping.org/files/2016/COBIDASreport.pdf"
        [[params.footer.links.links]]
            title = "OHBM Tutorials"
            url = "https://www.ohbmbrainmappingblog.com/tutorials.html"

        [[params.footer.links]]
            header = "More Links"
        [[params.footer.links.links]]
            title = "OHBM Open Science Special Interest Group"
            url = "https://ossig.netlify.app/"
        [[params.footer.links.links]]
            title = "other"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Duis neque nisi sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum amet varius"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""
