[[main]]
    name = "About us"
    weight = 30
[[main]]
    name = "Symposia"
    weight = 30
[[main]]
    name = "Roundtable"
    weight = 30
[[main]]
    name = "Kids Review"
    weight = 30    
[[main]]
    name = "Publications"
    weight = 30  
[[main]]
    name = "Links"
    weight = 30   
[[main]]
    name = "Contact us"
    weight = 30   
[[main]]
    parent = "Kids Review"
    name = "2020"
    weight = 35
[[main]]
    parent = "Kids Review"
    name = "2021"
    weight = 36
[[main]]
    parent = "Kids Review"
    name = "2022"
    weight = 37
