[[main]]
    name = "About Us"
    weight = 30
[[main]]
    parent = "About Us"
    name = "Our Mission"
    weight = 31
[[main]]
    parent = "About Us"
    name = "Our team 2022-23"
    weight = 32    
[[main]]
    parent = "About Us"
    name = "Past members"
    weight = 33  
[[main]]
    parent = "About Us"
    name = "OHBM Code of Conduct"
    weight = 34  
[[main]]
    name = "Symposia"
    weight = 30
[[main]]
    parent = "Symposia"
    name = "2020"
    weight = 31
[[main]]
    parent = "Symposia"
    name = "2021"
    weight = 32
[[main]]
    parent = "Symposia"
    name = "2022"
    weight = 33
[[main]]
    name = "Roundtable"
    weight = 30
[[main]]
    parent = "Roundtable"
    name = "2020"
    weight = 31
[[main]]
    parent = "Roundtable"
    name = "2021"
    weight = 32
[[main]]
    parent = "Roundtable"
    name = "2022"
    weight = 33
[[main]]
    name = "Kids Review"
    weight = 30   
    url = "/kidsreview" 
[[main]]
    parent = "Kids Review"
    name = "2020"
    weight = 31
    url = "/kidsreview/2020"
[[main]]
    parent = "Kids Review"
    name = "2021"
    weight = 32
    url = "/kidsreview/2021"
[[main]]
    parent = "Kids Review"
    name = "2022"
    weight = 33
    url = "/kidsreview/2022"
[[main]]
    name = "Publications"
    weight = 30  
[[main]]
    name = "Links"
    weight = 30   

