[[main]]
    name = "Dropdown"
    weight = 30
[[main]]
    parent = "Dropdown"
    name = "About us"
    weight = 31
[[main]]
    parent = "Dropdown"
    name = "Symposia"
    weight = 32
[[main]]
    parent = "Dropdown"
    name = "Roundtable"
    weight = 33
[[main]]
    parent = "Dropdown"
    name = "KidsReview"
    weight = 34
[[main]]
    parent = "KidsReview"
    name = "2020"
    weight = 35
[[main]]
    parent = "KidsReview"
    name = "2021"
    weight = 36
[[main]]
    parent = "KidsReview"
    name = "2022"
    weight = 37